version: '3.7'

services:
    alphakill-tweebotdb:
        image: postgres:12-alpine
        container_name: alphakill-tweebotdb
        ports:
            - "5432:5432"
        env_file: 
            - env/.db.env
    alphakill-tweebot:
        build:
            context: .
            dockerfile: dockerfile
        container_name: alphakill-tweebot
        volumes:
            - .:/src/alphakill-tweebot/
        ports:
            - "5000:5000"
        env_file:
            - env/.env.dev
        depends_on:
            - alphakill-tweebotdb
    alphakill-tweebot-pgadmin:
        container_name: alphakill-tweebot-pgadmin
        image: dpage/pgadmin4
        env_file: 
            - env/.pgadmin.env
        ports:
            - "5050:80"
        depends_on:
            - alphakill-tweebotdb
